### ISSUE TITLE
device database

### ISSUE THREAD

**Issue by lollul** [hwhw/zigbee-lua#1]
Hello!
Let me first thank you for sharing this exciting project!
I'm trying to run zigbee-lua on a PI/raspbian now but in the long term I hope this can be something I could run on a openwrt router as there is no hope I could get zibee2mqtt running on a MIPS router even with 128MB RAM. I just don't want another PI running 24/7 just as a zigbee<->mqtt  bridge.

I'm completely new to lua therefore please excuse my dumb questions...

First of all I'm not sure what is the best way to get the dependent lua libraries. So far I've tried luarocks and installed:
luarocks install inspect
luarocks install ljsyscall
luarocks install luabitop
luarocks install json-lua
There was a problem with the json libary - had to move it to a place expected by luajit, but expect this is just a little problem with raspbian and luarocks.
Please let me know if there is a better way to set up lua libraries.

Then, I'm not sure if the zigbee-lua server is supposed to create its device database or should I do something manually. On start I get:
<ERR> Zigbee: cannot open database file device_database.json, error: device_database.json: No such file or directory

It would seem I've managed to pair a Xiaomi Aquara WXKG11LM switch because I do get plenty of debugging output each time I press the button. The list-devs.sh script does not return any devices though which I guess is a result of the missing device_database.json file.
The same switch was paired on zigbee2mqtt on the same CC2531 previously... not sure if CC2531 just 'remembers' it or the pairing actually worked (sorry, lost the logs with all the excitement).

Also, sometimes it crashes:
`[2019-01-29 15:16:46] <DBG> srv: got event on fd 4
[2019-01-29 15:16:46] <DBG> dongle-cc2530//dev/ttyACM0: SOF found
[2019-01-29 15:16:46] <DBG> dongle-cc2530//dev/ttyACM0|mt: got MT command: type AREQ (2), subsystem ZDO (0x05), command id 0x84, data:
45 84 9D D6 00 9D D6 10 01 04 01 03 01 01 03 00   E...............
00 12 00 03 00 01 00 00                           ........

[2019-01-29 15:16:46] <DBG> dongle-cc2530//dev/ttyACM0|mt: MT command AREQ_ZDO_SIMPLE_DESC_RSP, payload:
{
  DeviceId = 259,
  DeviceVersion = 1,
  Endpoint = 1,
  InClusterList = { 0, 18, 3 },
  Len = 16,
  NwkAddr = 54941,
  OutClusterList = { 0 },
  ProfileId = 260,
  SrcAddr = 54941,
  Status = 0
}
[2019-01-29 15:16:46] <DBG> srv: removed FD 5 from epoll group
[2019-01-29 15:16:46] <DBG> ctx|task: task zigbee_provisioning resuming
[2019-01-29 15:16:46] <DBG> ctx|task: task zigbee_provisioning finished
[2019-01-29 15:16:46] <ERR> ctx|task: task zigbee_provisioning aborted with error: /usr/local/share/lua/5.1/lib/json-lua/json.lua:706: JSON:encode must be called in method format, stack traceback:
        [C]: in function 'assert'
        /usr/local/share/lua/5.1/lib/json-lua/json.lua:706: in function 'onEncodeError'
        /usr/local/share/lua/5.1/lib/json-lua/json.lua:1396: in function 'encode'
        ./interfaces/zigbee.lua:32: in function 'save'
        ./interfaces/zigbee.lua:109: in function <./interfaces/zigbee.lua:105>
luajit: ./lib/srv-epoll.lua:114: ./lib/ctx.lua:212: /usr/local/share/lua/5.1/lib/json-lua/json.lua:706: JSON:encode must be called in method format
stack traceback:
        [C]: in function 'char_reader'
        ./lib/srv-epoll.lua:114: in function 'on_readable'
        ./lib/srv-epoll.lua:68: in function 'run'
        ./main.lua:4: in main chunk
        [C]: at 0x00013bf8
`
Could it be I've installed wrong json-lua library?

Appreciate your help!

**Comment by lollul** [comment]
Noticed now multiple libraries are already in your repository as submodules. With these libraries it no longer crashes. Forgive my ignorance.
I still wonder whats going on with the device database file and if there is already a way to get MQTT integration. The mqtt.lua appears to be a stub...or I just don't know how to use it.

**Comment by hwhw** [comment]
Hi! Thanks for saying "thanks" :-) Well, I guess without any experience in Lua programming, there's a steep learning curve - especially since the whole thing is not really up to terms with my own aspirations with regard to the level of documentation and the amount of tests (nil). However, this now runs my own setup of about 20 Zigbee light bulbs (Osram, Philips) and about 20 buttons, switches, cubes, presence detectors and climate sensors (all of them Aqara).

You're right, with the submodules in place it is very much self-contained. The httpd subsystem (which *is* already functional in principle, but there's just no application example, I think) needs a libmicrohttpd library installed in the system and the mqtt interface will need a libmosquitto. However, you're right: the mqtt part is still a stub. It will have to be integrated with the main event loop, which currently is very generic and linux specific - it uses epoll() via ljsyscall. I have all of the integration outlined in my head but did not yet get to finish it. A rough estimate: in 2-4 weeks, it should be there.

The device database file *ought* to be created automatically, I thought. However, the path (as in the config file) must exist - in my example config.lua file, there is no path, so it would be the current working directory of the calling process (like, your shell or a script?). To make things sure, you could just configure an absolute path there (and make sure it is writable).

Aqara devices are really bitchy when it comes to pairing. Well, this is not exactly true. They do pair just fine. But the next step - I've called it "provisioning" - is to enumerate its clusters and endpoints (which is Zigbee lingo). While the pairing is something that is initiated by the end device, the latter is initiated by the coordinator software and consists of querying - in multiple steps - for descriptors. As the end devices are heavily battery optimized, this can get quite cumbersome. *However*, these descriptors are absolutely identical for a certain type of end device. So one can simply copy a device database entry (which consists of the queried descriptors) for a new one. Sadly, not a lot of this has yet easily accessible frontends.

All in all, I think this software might do what you want - and it *is* very much capable to run on much lower resources than the monstruous nodejs runtime. I guess MIPS with 128MB of RAM ought to be fine. I think it might be the most sensible to wait for the mqtt interface to be completed. I need it to forward my sensor data, so I'll definitely implement it soonish. First priority of my home automation needs was scriptability, which is more or less finished (well, lots of polishing ought to be done, but well...), so now it is time to focus on the secondary tasks.

**Comment by hwhw** [comment]
As a reference: the instance running on my Pi for about 20 days straight now has a peak virtual (!) memory usage of 8432kB, of which 7052kB are the RSS. It has used 5m51s of CPU time over those days, controlling all light switching and changing in my apartment.

**Comment by lollul** [comment]
I've tried again and this time I've simply 'touched' device_database.json file end then attempted to pair a device. It appears to have worked the file got populated. So, now I have my first device paired (I guess):
       IEEE Addr |  NWK | Manu |             Name | EPs
00158d000213xxxx | 5de1 | 1037 |                - | 1 (in: 0000,0012,0003, out: 0000)

This is a button, when pressed I get this:
[2019-02-01 21:13:42] <DBG> srv: got event on fd 6
[2019-02-01 21:13:42] <DBG> dongle-cc2530//dev/ttyACM0: SOF found
[2019-02-01 21:13:42] <DBG> dongle-cc2530//dev/ttyACM0|mt: got MT command: type AREQ (2), subsystem AF (0x04), command id 0x81, data:
44 81 00 00 12 00 E1 5D 01 01 00 5C 00 C0 51 55   D......]...\..QU
00 00 08 18 2B 0A 55 00 21 01 00 E1 5D 1D         ....+.U.!...].

[2019-02-01 21:13:42] <DBG> dongle-cc2530//dev/ttyACM0|mt: MT command AREQ_AF_INCOMING_MSG, payload:
{
  ClusterId = 18,
  Data = { 24, 43, 10, 85, 0, 33, 1, 0 },
  DstEndpoint = 1,
  GroupId = 0,
  LinkQuality = 92,
  SecurityUse = 0,
  SrcAddr = 24033,
  SrcEndpoint = 1,
  Timestamp = 5591488,
  TransSeqNumber = 0,
  WasBroadcast = 0
}
[2019-02-01 21:13:42] <DBG> ctx|task: task cc253x_incoming_message resuming
[2019-02-01 21:13:42] <INF> dongle-cc2530//dev/ttyACM0/af: incoming message from 0x5de1, clusterid 0x0012, dst EP 1
[2019-02-01 21:13:42] <DBG> ctx|task: task zigbee_rx_handler resuming
[2019-02-01 21:13:42] <DBG> Zigbee: parsed: {
  FrameControl = { "FrameTypeGlobal", "DirectionFromServer", "DisableDefaultResponse" },
  GeneralCommandFrame = {
    CommandIdentifier = "ReportAttributes",
    ReportAttributes = {
      AttributeReports = { {
          Attribute = {
            Type = "uint16",
            Value = 1
          },
          AttributeIdentifier = 85
        } }
    }
  },
  TransactionSequenceNumber = 43
}
[2019-02-01 21:13:42] <DBG> ctx|task: task zigbee_rx_handler waiting
[2019-02-01 21:13:42] <DBG> ctx|task: task cc253x_incoming_message waiting
[2019-02-01 21:13:42] <DBG> dongle-cc2530//dev/ttyACM0|mt: MT command nil, remaining data in package: E1 5D 1D                                          .].

[2019-02-01 21:13:42] <DBG> srv: waiting for epoll events

I've tried using using the set-name.sh script. Not sure what the device 'id' is. I've tried many ways, it worked in the end although I can't reproduce it... Its as if there is a delay between what set_name.sh does and what list-devs.sh shows.

I only have Aqara switches (buttons) and temeprature sensors right now. But I can't figure out how I could use either the TCP or HTTP interfaces to detect the events they send.
I guess there is some magic with NC needed?

I feel bad about asking such basic things but if you have some example script - please share. Thanks!

**Comment by lollul** [comment]
A little progress report from openwrt front - it works just the same as on raspbian!
This is on Xiaomi router 3G and openwrt snapshot of today. Steps:
- opkg install luabitop
- there was no luajit built for my architecture (mipsel_24kc) but luajit can be easily compiled 'standalone'. just have to build the openwrt toolchain and then do "make package/luajit/compile'
- then I've had these problems:
luajit: lib/ljsyscall/syscall/linux/fcntl.lua:25: table index is nil
stack traceback:
        lib/ljsyscall/syscall/linux/fcntl.lua:25: in function 'init'
        lib/ljsyscall/syscall/syscalls.lua:24: in function 'init'
        lib/ljsyscall/syscall.lua:43: in main chunk
        [C]: at 0x00451740
        [C]: in function 'require'
        ./lib/srv-epoll.lua:8: in main chunk
        [C]: in function 'require'
        ./lib/ctx.lua:9: in main chunk
        [C]: in function 'require'
        ./main.lua:2: in main chunk
        [C]: at 0x004040ac
and:
luajit: lib/ljsyscall/syscall/linux/fcntl.lua:37: table index is nil
stack traceback:
        lib/ljsyscall/syscall/linux/fcntl.lua:37: in function 'init'
        lib/ljsyscall/syscall/syscalls.lua:24: in function 'init'
        lib/ljsyscall/syscall.lua:43: in main chunk
        [C]: at 0x00451740
        [C]: in function 'require'
        ./lib/srv-epoll.lua:8: in main chunk
        [C]: in function 'require'
        ./lib/ctx.lua:9: in main chunk
        [C]: in function 'require'
        ./main.lua:2: in main chunk
        [C]: at 0x004040ac
but it turns out its good enough to just comment out lines: lib/ljsyscall/syscall/linux/fcntl.lua:25 and lib/ljsyscall/syscall/linux/fcntl.lua:37. These are lines with 'c.F.ADD_SEALS' and 'c.F.GET_SEALS'...whatever that is ;-)
With this I get the same output as on raspberry - aqara button press shows up on debugging console.
Top shows VSZ size of about 6K - this is quite small - comparable to dnsmasq or uhttpd processes!

All I need now is a way to receive the zigbee events on TCP port, parse them and trigger mosquitto_pub.  I imagine some LUA/ZCL script magic needs to be passed to netcat for that...

**Comment by hwhw** [comment]
Well... MQTT client is now in place. Maybe start with a try to use that? :-) Have a look at mqtt-environment.lua (or rather, run the whole thing like "luajit main.lua mqtt-environment").

**Comment by lollul** [comment]
A Zigbee to MQTT bridge is officially running (on openwrt)! Thank you!

The output of mosquitto_sub with format -F '%t %p' for aquara switch WXKG11LM:
`/zigbee-lua/00158d0002136924/18/1 {"FrameControl":["FrameTypeGlobal","DirectionFromServer","DisableDefaultResponse"],"TransactionSequenceNumber":130,"GeneralCommandFrame":{"CommandIdentifier":"ReportAttributes","ReportAttributes":{"AttributeReports":[{"AttributeIdentifier":85,"Attribute":{"Type":"uint16","Value":1}}]}}}`
and the value changes to 2 if button is pressed twice. This is perfect!
For the temp/humidity sensor Mijia WSDCGQ01LM I get three messages...guess 2nd and 3rd are temperature and humidity values which would need some conversion:
`/zigbee-lua/00158d0002556234/0/1 {"FrameControl":["FrameTypeGlobal","DirectionFromServer","DisableDefaultResponse"],"TransactionSequenceNumber":50,"GeneralCommandFrame":{"CommandIdentifier":"ReportAttributes","ReportAttributes":{"AttributeReports":[{"AttributeIdentifier":5,"Attribute":{"Type":"string","Value":"lumi.sensor_ht"}}]}}}
/zigbee-lua/00158d0002556234/1026/1 {"FrameControl":["FrameTypeGlobal","DirectionFromServer","DisableDefaultResponse"],"TransactionSequenceNumber":51,"GeneralCommandFrame":{"CommandIdentifier":"ReportAttributes","ReportAttributes":{"AttributeReports":[{"AttributeIdentifier":0,"Attribute":{"Type":"int16","Value":2542}}]}}}
/zigbee-lua/00158d0002556234/1029/1 {"FrameControl":["FrameTypeGlobal","DirectionFromServer","DisableDefaultResponse"],"TransactionSequenceNumber":52,"GeneralCommandFrame":{"CommandIdentifier":"ReportAttributes","ReportAttributes":{"AttributeReports":[{"AttributeIdentifier":0,"Attribute":{"Type":"uint16","Value":5285}}]}}}`

I did get a couple of "segmentation fault" and "luajitBus error". I'm not sure if I should open separate issues on these. I mean I don't want to put any pressure on you especially since you didn't plan to add MQTT at this time.

**Comment by hwhw** [comment]
I'm a bit unsure about those segfaults and bus errors. Of course, they might be bad memory accesses. However - can you try running luajit with the "-j off" flag? I've seen the JIT create some havoc before (in my case, a very recent luajit on aarch64)... The code uses Lua coroutines extensively (a lot of Lua code manages to not use them at all) and I think there are some less trodden paths with JIT-compilation and coroutines...

In all honesty, a bit of data parsing (and error handling when converting to JSON) should probably be done - I just pulled the easiest approach to MQTT publishing out of my hat for this quick example.

As for the climate sensor values: the factor is just a power of ten for conversion to more common units :-) The data being three separate messages is due to the sensor sending three separate Zigbee packets.

**Comment by lollul** [comment]
Yes, "-j off" flag has helped - no more segfaults. Zigbee-lua survived the night with two climate sensors and switches working well. 
I think the "Bus error" is/was related to MQTT. I got it once more when restarting zigbee-lua. But second start attempt worked fine. I didn't test further assuming its just a temporary glitch with connection to mqtt server.
Even in current state I can easily distinguish temperature and humidity values - one is reported as int16 while the other is uint16. This is great!

I also get these mysterious packets:
`/zigbee-lua/00158d0002556234/0/1 {"FrameControl":["FrameTypeGlobal","DirectionFromServer","DisableDefaultResponse"],"TransactionSequenceNumber":114,"GeneralCommandFrame":{"CommandIdentifier":"ReportAttributes","ReportAttributes":{"AttributeReports":[{"AttributeIdentifier":65281,"Attribute":{"Type":"string","Value":"\u0001!�\u000b\u0004!�\u0013\u0005!\t\u0000\u0006$\u0001\u0000\u0000\u0000\u0000d)\u001f\be!�\u0013\n!\u0000\u0000"}}]}}}`
Seems they are UTF codes, but they don't make any sense to me...maybe Xiaomi specifc stuff.

If you don't mind I'd like to spread the word about your wonderful project among openwrt community.
There are a lot of things I'd like to ask but I don't want to steal your time. Many thanks again!

**Comment by hwhw** [comment]
Yep, that's Xiaomi prorietary. In fact, the parser is already in place - but not in the very simplicistic MQTT env I rapidly prototyped. Its most interesting part is probably the battery voltage, which is a useful thing to look at once in a while.

Of course, I don't mind at all, feel free to spread the word :-)

Also, please ask any questions you like! I so far enjoy answering them and in fact I'm happy that someone could make some use of software I wrote! And don't hesitate to open a new issue per question - it will get a bit convoluted otherwise. If you don't mind, I would close *this* particular issue in a few days to maintain some kind of order in the issue list.

**Comment by hwhw** [comment]
Since I had code to re-use, I added parsing of this Aqara proprietary data. I forgot what most of it is, but you should easily recognize the attribute giving coin cell battery voltage in millivolts :-)

**Comment by hwhw** [comment]
Oh, and I only now realize you were searching for something to distinguish the values: The MQTT messages *topic* includes the IEEEaddress (which should be unique, globally, for the device), the Zigbee *Cluster* identifier (as a decimal number, rather than the hexadecimal number that is used in the ZCL spec all the time) and the device Endpoint. The *Cluster* identifier is specific to the kind of the value (in this case). The ZCL spec is huge, but in any case certainly worth a look when you want to look up the defined meaning of the values (which does not work for the proprietary Aqara status report, though).

**Comment by lollul** [comment]
Yes, I've noticed the Cluster Identifier meaning...1026 is temperature, 1029 humidity etc.
The mqtt_environment changes are a big help. Now I can use it as an example how to parse things... 
I've noticed the Mija sensor WSDCGQ01LM sends a bit different 'aqarareport' - there is only one 'AttributeReport' entry and no ManufacturerCode is sent. I'm attaching a change I just did to show that thanks to your example even a noob like me can do stuff!
[mqtt_environment.patch.txt](https://github.com/hwhw/zigbee-lua/files/2831632/mqtt_environment.patch.txt)

**Comment by lollul** [comment]
While playing with my mqtt_environment I've realised I'm missing two features. I've made these silly, little patches:
1. ability for MQTT client to pass Retain parameter - this is helpful with my temperature sensors
[0003-export-MQTT-client-QoS-and-Retain-parameters.patch.txt](https://github.com/hwhw/zigbee-lua/files/2849277/0003-export-MQTT-client-QoS-and-Retain-parameters.patch.txt)

2. ability to pass LinkQuality to MQTT via ZCL
[0004-pass-linkquality-to-ZCL.patch.txt](https://github.com/hwhw/zigbee-lua/files/2849278/0004-pass-linkquality-to-ZCL.patch.txt)

I don't know how much sense these make for you...just thought I'll share. Thanks!

**Comment by hwhw** [comment]
Well, that's some lightweight changes indeed - and I certainly see their use (my approach usually is along these lines: wait until need arises, then extend sensibly). I think I'll incorporate them, as soon as I dig into the code again. So: thank you!

**Comment by hwhw** [comment]
As I told before, I'm gonna close this issue, since it is more a discussion thread. Don't feel unwelcomed here, the opposite is true! Please open new issues for any questions you have, patches you've written, bugs you've encountered - I'm always most thankful!

**Comment by hwhw** [comment]
Segfaults and bus errors should be gone with latest changes to MQTT client implementation, which just couldn't work in its thread-based variant. Interesting it did work at all, even without JIT. Now, running with JIT should work.
