### ISSUE TITLE
mqtt_client: random segfaults

### ISSUE THREAD

**Issue by Perlovka** [hwhw/zigbee-lua#2]
Hi,

I've tried to create testing env, but app mostly segfaults at random point.
I have two Aqara LED bulbs, the goal was to control them via mqtt.

Sometimes it start sucessfully, and works as expected, e.g. it reports status from bulbs

```shell
mosquitto_sub -t /zigbee-lua/event/Lamp
{"state":1,"bright":255,"temp":370}
```

 and I could get devices via

`mosquitto_pub -t /zigbee-lua/devices/get -n`

and could control color temp with

`mosquitto_pub -t /zigbee-lua/devices/Lamp2/set -m '{ "ctemp": 270}'`

Here is an environment file:
```lua
local ctx = require"lib.ctx"
local U = require"lib.util"
local D = require"interfaces.zigbee.any"
local json = require"lib.json-lua.json"
local M = ctx.interfaces.mqtt_client[1]

local E = U.object:new()

local devices = ctx.interfaces.zigbee[1].devices:names()
for _,dev in ipairs(devices) do
    E[dev] = D:new{id=dev}
---[[
    E[dev]:on_aqara_report(function (d)
        if d.ReportAttributes then
            local state = { lq = d.linkquality }
            for _, r in ipairs(d.ReportAttributes) do
                if r.AttributeIdentifier == 100 then
                    state.state = r.Attribute.Value
                end
                if r.AttributeIdentifier == 101 then
                    state.bright = r.Attribute.Value
                end
                if r.AttributeIdentifier == 102 then
                    state.temp = r.Attribute.Value
                end
            end
            local ok, msg_json = pcall(json.encode, state)
            if ok then M:publish(string.format("/zigbee-lua/event/%s", dev), msg_json) end
        end
    end)

    M:subscribe(string.format("/zigbee-lua/devices/%s/set", dev))

    ctx.task{function()
        for ok, msg in ctx:wait_all({"mqtt_client", "message"}, function(msg) return msg.topic == string.format("/zigbee-lua/devices/%s/set",dev) end) do
            local ok, t = pcall(json.decode, msg.payload)
            if ok then
                for k,v in pairs(t) do
                    if k == 'ctemp' then E[dev]:ctemp(v)
                    U.DEBUG("env", "payload: %d", v)
                    end
                end
            end
            M:publish(string.format("/zigbee-lua/event/%s", dev), string.format("%s",t.ctemp))
        end
    end}
--]]
end

-- MQTT subscribing: We use this to open the network for joining
M:subscribe("/zigbee-lua/permit_join")
ctx.task{name="mqtt_permit_join",function()
  for ok, msg in ctx:wait_all({"mqtt_client", "message"}, function(msg) return msg.topic == "/zigbee-lua/permit_join" end) do
    U.DEBUG("mqtt_environment", "got permit_join message via MQTT, opening network for devices")
    -- TODO: timeout handling etc
    ctx:fire({"Zigbee","permit_join"},{include={0xfffc}})
  end
end}

---[[
M:subscribe("/zigbee-lua/devices/get")
ctx.task{name="mqtt_list_devices",function()
  for ok, msg in ctx:wait_all({"mqtt_client", "message"}, function(msg) return msg.topic == "/zigbee-lua/devices/get" end) do
    U.DEBUG("mqtt_environment", "got list message via MQTT")

    local ok, msg_json = pcall(json.encode, {type="list", event="devices", data = ctx.interfaces.zigbee[1].devices})
    if ok then M:publish("/zigbee-lua/devices", msg_json) end
  end
end}
--]]
return E
```

**Comment by Perlovka** [comment]
Seems that problem is somewhere in M:subscribe, if I comment out all of them, there are no segfaults anymore.

P.S. Moving all subscribe tasks to the end of module solves the problem:
```lua
...

for _,dev in ipairs(devices) do
    M:subscribe(string.format("/zigbee-lua/devices/%s/set", dev))
end
M:subscribe("/zigbee-lua/devices/get")
M:subscribe("/zigbee-lua/permit_join")

return E
```

**Comment by hwhw** [comment]
Yes, I think I'm experiencing the same erratic behaviour. I think I need to have a closer look at integrating the MQTT library with the main event loop. Currently it is using its own thread, which seems to be broken. I guess this is due to callbacks that run in the parallel thread from libmosquitto - and accessing the same Lua state is bound to crash, I guess. I'll look deeper into libmosquitto. I like other aspects of its interface and am not really fond of dumping it and switching to a different, more friendly library...
Thanks for the report! I'm going to investigate - however, probably this will take a few days!

**Comment by hwhw** [comment]
Possibly e2eb62558c09d603639006e99ceeb6c7a1b980c2 does fix this bad behaviour. It is almost completely untested and might in fact not work at all - I just ran a simple test. Will do more testing in a few days.

**Comment by hwhw** [comment]
Unfortunately, it still seems to be missing a bit. It's hitting timeouts related to the MQTT keepalive mechanism here. I think the broker sends a ping that is not answered atm. Will look into it further.

**Comment by hwhw** [comment]
OK, should be fixed in 29c5ab7a3e4a45a1272939097df9545b86d268c0 - it's currently being tested within my production environment, running for about 10-15 minutes without hickups now :-)

**Comment by Perlovka** [comment]
Thanks!

**Comment by hwhw** [comment]
BTW, you're the second user (except me) of this code I'm aware of :-) I'm still a bit hesitant to give it any exposure, admittedly - looking in awe at the amount of "end user fallout" in the issues of https://github.com/Koenkk/zigbee2mqtt, I somewhat intentionally kept this code a bit "hacky". It's very interesting to see that you were able to make use of it. Maybe I feel motivated soon to fletch out the documentation a bit more (or rather, start to write it in the first place) :-D I hope you can or could make some use of it. And I'm always interested to hear about similar stuff!

Closing this now since I consider the bug solved - code is running since >24h now here and seems to be quite robust. (JIT enabled! "Broken" JIT was likely caused to broken - since threading - code, too.)
