### ISSUE TITLE
Running as a service

### ISSUE THREAD

**Issue by Perlovka** [hwhw/zigbee-lua#5]
Hi,

After refactoring, my zigbee-lua setup is broken ;) . I've used main.lua code as service binary (https://github.com/Perlovka/portage-overlay/blob/master/dev-lua/zigbee-lua/files/zigbee-lua), which has been launched by init script. 
And environment file has been set in config.lua:

```lua
return {
  srv_implementation = "lib.srv-epoll",
  systemd = false,
  environment = "test-env",
  interfaces = {
```
That was very handy, but now I'm required to run an environment file itself, and this is not so flexible as before.

Could we revert to the old behavior? :wink: 

Or even better:
1. Create some lua script that will act as system service binary.
2. It should read config file and run appropriate environment.
3. It should search config file either in place, provided by command line (like **zigbee-lua -c /etc/zigbee-lua/config.json**) or in current directory.
4. Config file should not be a lua code (because otherwise you should add it's path to lua **package.path**). Easiest option - json format, it can be easy converted into lua table. 

How do you think about it?

**Comment by hwhw** [comment]
I don't think that reverting is a good idea.
1./2. can be archieved by just having a "proxy lua file" that reads config and runs a certain environment, I think. I'm not sure if this is something to include in the codebase as it really distracts from the state of things right now.
4. I don't see the benefits from that, frankly - might be that I don't really understand your reasoning since I don't see how package.path is concerned here, as you could easily go for dofile() if require()/include() has too much magic for your taste going on?

BTW, I don't think that much else has changed, so the easiest approach for now might be to just run the pre-refactoring status? I'm really hesitant to change what there is now. Reason for the refactoring was to have a single place (environment file) as a starting point, not two (config/environment). Note that with the new state of things, you can just include the config table into the environment (that require"config" there can just be replaced by the config table).

**Comment by hwhw** [comment]
This is about what the old main.lua did (but it uses dofile() more consequently), with a bit more flexibility when it comes to the config.lua file/path. Call syntax is ```main.lua [<config file path>] <environment file>```.

```
#!/usr/bin/env luajit
if not arg[1] then error("need to give environment path") end
local config = arg[2] and arg[1] or "./config.lua"
require"lib.ctx"(dofile(config), dofile(arg[2] or arg[1]))
```

**Comment by Perlovka** [comment]
**dofile** seems the right thing! Thanks, I'll try it )
